name: 'Terraform Security'

on:
  workflow_call:
    inputs:
      terraform-path:
        required: true
        type: string

jobs:
  sca-scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
#      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          framework: terraform
          directory: ${{ inputs.terraform-path }}
          # CLI output and a results.sarif file
          output_format: cli,sarif
          output_file_path: console,results.sarif
          skip_check: "CKV_AZURE_227,CKV_AZURE_117,CKV_AZURE_7,CKV_AZURE_171,CKV_AZURE_115,CKV_AZURE_6,CKV_AZURE_116,CKV_AZURE_4,CKV_AZURE_232,CKV_AZURE_141,CKV_AZURE_226,CKV_AZURE_168,CKV_AZURE_172,CKV_AZURE_170,CKV2_AZURE_29"

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3

        # Results are generated only on a success or failure
        # this is required since GitHub by default won't run the next step
        # when the previous one has failed. Security checks that do not pass will 'fail'.
        # An alternative is to add `continue-on-error: true` to the previous step
        # Or 'soft_fail: true' to checkov.
        if: success() || failure()
        with:
          sarif_file: results.sarif
